# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KpFind
                                 A QGIS plugin
 Finds geodetic distance along and to the side of a line
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-06
        copyright            : (C) 2020 by Milen Iliev
        email                : m.iliev@posteo.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
#we are importing the geographiclib module from the plugin directory:
import site
import os
site.addsitedir(os.path.abspath(os.path.dirname(__file__) + '/ext-libs'))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KpFind class from file KpFind.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .KP_Find import KpFind
    return KpFind(iface)
